### ISSUE TITLE
Update CI badge on the ReadMe

### ISSUE THREAD

**Issue by dzimmanck** [korken89/smlang-rs#30]
The CI badge on the ReadMe appears out-of-date, as it shows up as failing.

**Comment by dzimmanck** [comment]
@korken89, I am not very familiar with the travis CI system.  If you want I can port this to the integrated CI with Github actions.  Otherwise I think this one is for you.  Would be good if this was fixed though because it is one of the first things people look at to determine if a crate is well maintained.

**Comment by korken89** [comment]
The crate already uses Github Actions, just that the badge is not used.
If you want you can update the badge, or remove it.

**Comment by dzimmanck** [comment]
@korken89

OK, so just the badge was pointing to one generated by an older CI system.  I submitted PR #33 which points these to the SVG badges generated by Github actions.  This will make the repo look much more appealing to potential users.  No one likes to see "fail" at the top of the master branch when considering using a library in production.

**Comment by dzimmanck** [comment]
Closed by PR #33
