### ISSUE TITLE
Wish:  Add link to graphviz translator

### ISSUE THREAD

**Issue by stappersg** [korken89/smlang-rs#40]
Having a hard time finding a link of a _smlang DSL_ to _graphviz syntax_ translator  was why this "wish issue" was created.

I hope/think/assume/wish there is already such translator, because more people like to generate nice images of the `smlang` state machines with [Graphviz](https://graphviz.org/).

**Comment by Yatekii** [comment]
There is a featureflag for this which generates an SVG for you.

**Comment by stappersg** [comment]
With that clue did I go back the `smlang-rs` source.

Now there is #41.

**Comment by stappersg** [comment]
And with #42 there is no need to keep this issue open.
