### ISSUE TITLE
Syntax for adding derive/procedural macros on `States` and `Events`

### ISSUE THREAD

**Issue by oblique** [korken89/smlang-rs#55]
Some users may want to use derive on `States` and `Events`.

A possible syntax can be:

```rust
statemachine! {
    transitions: {
        *State1 + Event1 [guard1] / action1 = State2,
    }
    states_derive: {
        #[derive(Debug, Clone)]
    }
    events_derive: {
        #[derive(Debug, Clone)]
    }
}
```

Any comments or other ideas?

**Comment by ryan-summers** [comment]
I don't think this should be explicitly requested, but rather implicitly provided.

What I mean by that, is that states and events should follow https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits and these types should be implemented by default wherever possible.

**Comment by oblique** [comment]
That would be great, however I think it will hard and close to impossible to implement it.

The impossible part is when `States` or `Events` take as data a non-std type, which we do not know that traits it implements.

**Comment by oblique** [comment]
Correct. Didn't think about it :)
