### ISSUE TITLE
Is there support for multiple guarded transitions for a state and a triggering event ?

### ISSUE THREAD

**Issue by dkumsh** [korken89/smlang-rs#71]
Is there support for multiple guarded transitions for a state and a triggering event ?

As it is described [here](https://en.wikipedia.org/wiki/UML_state_machine#Guard_conditions),
the guards should enable/disable transitions based on the value of the extended variables and event parameters.

I would expect that guards should allow transitions from  (state,event) to different states, same way as it works in Boost SML and many other state machine implementations.

The article referenced above says:

In [extended state machines](https://en.wikipedia.org/wiki/UML_state_machine#Extended_states), a transition can have a [guard](https://en.wikipedia.org/wiki/UML_state_machine#Guard_conditions), which means that the transition can "fire" only if the guard evaluates to TRUE. **A state can have many transitions in response to the same trigger**, as long as they have nonoverlapping guards; however, this situation could create problems in the sequence of evaluation of the guards when the common trigger occurs. The UML specification[[1]](https://en.wikipedia.org/wiki/UML_state_machine#cite_note-UML2_2-1) intentionally does not stipulate any particular order; rather, UML puts the burden on the designer to devise guards in such a way that the order of their evaluation does not matter. Practically, this means that guard expressions should have no side effects, at least none that would alter evaluation of other guards having the same trigger.

Is there support for multiple guarded transitions for a state and a triggering event ?
If yes, could you please show how to do it, otherwise would it be possible to implement it?

**Comment by ryan-summers** [comment]
If the initial state and triggering event are identical, I do not believe we support multiple ending states based on different guards. You would have to use a different event type to accomplish this instead.

Can you clarify what you're looking to do exactly?

**Comment by dkumsh** [comment]
Something like this:
State1 + Event1 [ guard2] / action2 = State2,
State1 + Event1 [ guard3] / action_3 = State3,
In State1 we receive Event1 and depending on which of the guards returns true, we transition either to State2 or to State3. 
We can assume that the guards are not-overlapping.

**Comment by ryan-summers** [comment]
Interesting that BoostSML indeed supports this. I'd be happy to review a PR for it, but this definitely feels non-trivial to add.

By the way, I don't see how your example would require this. It seems like you could probably implement this with different state transitions to work around this, but that's just my take.

**Comment by dkumsh** [comment]
Thanks for you reply. I made a change on my local clone. Indeed it is not a simple change. 
I am now trying to use it to implement a state machine in my project.
Once I feel comfortable with the change I will push a PR for review (maybe within a week or two). 
I hope it won't break any existing functionality.
It now passes all tests except two tests validating state/event duplicates as I had to allow the duplicates.
Will get back to you in a while

**Comment by dkumsh** [comment]
Hi Ryan, I am ready to push my commits for a review. Do I need to get permissions for that ? What should be the next steps ?

**Comment by dkumsh** [comment]
Current implementation only allows single function guards.
In addition to the PR above I implemented support for guard expressions (similar to Boost SML).
In the original library you can define a transition like :
State + Event [guard] / ...
where in square brackets it allows a single boolean guard function.
With the addition I describe it is now possible to specify **guard boolean expressions**, e.g :
State + Event [guard1 && ! guard2] / ...
I will push that code in a few days to my fork

**Comment by dkumsh** [comment]
Hello, could someone please review the [pull request](https://github.com/korken89/smlang-rs/pull/72) at their earliest convenience? Thank you!

**Comment by dkumsh** [comment]
@ryan-summers Tanks for providing the review!
