### ISSUE TITLE
Question: Is it possible to release a version 0.6.1?

### ISSUE THREAD

**Issue by vinicius-smartme** [korken89/smlang-rs#74]
Hello.

Would it be possible to release a version 0.6.1 with contains the Auto-derive feature? The implementation is available since the commit [a85caa0](https://github.com/korken89/smlang-rs/commit/a85caa0de8639a2a410d29b7754ab95402488997).

Thank you for this great crate.

Best regards.

**Comment by ryan-summers** [comment]
Currently waiting on the following PRs before I release:
* #73 
* #76

**Comment by vinicius-smartme** [comment]
Very good. Thank you.
