### ISSUE TITLE
Support for wildcard internal transitions

### ISSUE THREAD

**Issue by dkumsh** [korken89/smlang-rs#81]
I'am  adding a PR for [support for wildcard internal transitions](https://github.com/korken89/smlang-rs/pull/80).
I think this should be a valuable addition to DSL (non-breaking).
It is supported in boost::sml.
Please review

**Comment by dkumsh** [comment]
@ryan-summers  thanks for the review of this [PR.](https://github.com/korken89/smlang-rs/pull/80) . The branch is deleted. I still need the fork for my project until the new version is released to crates.io as. 
Are you planing to do that ?
It would be nice to have it.
Thanks

**Comment by ryan-summers** [comment]
Fixed in #80, I can look at a new release, but might try and cleanup the callbacks first.
